FROM openjdk:8u312-jdk-slim

ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ADD build/libs/grammerChecker-0.0.1-SNAPSHOT.jar app.jar
ENV JAVA_OPTS="-Dfile.encodeing=UTF-8"
ENTRYPOINT ["java", "-jar", "/app.jar"]