apiVersion: apps/v1
kind: Deployment
metadata:
  name: grammar-checker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grammar-checker
  template:
    metadata:
      labels:
        app: grammar-checker
    spec:
      containers:
        - name: grammar-checker
          image: tlgj255/base-image:grammar-checker
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
      imagePullSecrets:
        - name: my-secret